"""Resume evidence domain models and contracts."""

from src.resume_evidence.model import (
    AuthorityKind,
    CanonicalCorpus,
    CanonicalSourceRecord,
    ConfidenceLevel,
    DoctrineCandidate,
    DoctrineRecord,
    DoctrineUse,
    EditorialDimension,
    EditorialRating,
    EmploymentInterval,
    EvidenceConfidence,
    ExperienceConfidence,
    OutcomeCandidate,
    OutcomeRecord,
    OutcomeTier,
    PatternCard,
    ResumeRepresentation,
    ResumeVersionAttribution,
    RoleFamily,
    SCHEMA_VERSION,
    SourceKind,
    SourceRecord,
)
from src.resume_evidence.store import EvidenceBank, load_evidence_bank, lookup_outcomes

__all__ = [
    "SCHEMA_VERSION",
    "SourceKind",
    "OutcomeTier",
    "EvidenceConfidence",
    "ConfidenceLevel",
    "ResumeRepresentation",
    "ResumeVersionAttribution",
    "ExperienceConfidence",
    "RoleFamily",
    "AuthorityKind",
    "DoctrineUse",
    "EditorialDimension",
    "SourceRecord",
    "CanonicalSourceRecord",
    "EmploymentInterval",
    "EditorialRating",
    "OutcomeCandidate",
    "OutcomeRecord",
    "DoctrineCandidate",
    "DoctrineRecord",
    "PatternCard",
    "CanonicalCorpus",
    "EvidenceBank",
    "load_evidence_bank",
    "lookup_outcomes",
]
